server:
  port: 91

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

service-url:
  nacos-user-service: http://nacos-payment-provider