server:
  port: 82

spring:
  application:
    name: cloud-openfeign-consumer-order
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    openfeign:
      client:
        config:
          cloud-payment-service:
            # 连接超时时间
            connect-timeout: 4000
            # 读取超时时间
            read-timeout: 4000
      httpclient:
        hc5:
          enabled: true # Apache HttpClient 5 配置开启
      compression: # request & response 压缩配置开启
        request:
          enabled: true
          min-request-size: 2048 # 最小出发压缩的大小
          mime-types: text/xml, application/xml, application/json # 触发压缩的数据类型
        response:
          enabled: true
logging:
  level:
    cloud:
      cloud_common:
        apis: debug # feign 日志配置：logging.level + 含有 @FeignClient 注解的完整 package + debug
