server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: pay_routh_1 # 路由的 ID（类似 MySQL 主键 ID），没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service # 与 http://127.0.0.1:8001 同理 匹配后提供服务的路由地址，且模块需要添加 spring-cloud-loadbalancer 依赖
          predicates:
            - Path=/pay/gateway/get/** # 断言，路径相匹配的进行路由
            - Custom=diamond|gold|silver
        - id: pay_routh_2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**